services:
  rl:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}

    command: sleep infinity

    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      HISTFILE: /workspace/docker/.bash_history
      PROMPT_COMMAND: "history -a; history -n"
      MAD_ASSETS_PATH: ${MAD_ASSETS_PATH:-}

    volumes:
      - .:/workspace
      - ../mad_assets/models:${MAD_ASSETS_PATH:-}/models
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    stdin_open: true
    tty: true
    ipc: host
    network_mode: host

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
