services:
  rl:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}

    command: sleep infinity

    env_file:
      - .env

    environment:
      - DISPLAY=${DISPLAY}

    volumes:
      - .:/workspace
      - ../mad_assets/models:${MAD_ASSETS_PATH:-}/models
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    stdin_open: true
    tty: true
    ipc: host
    network_mode: host

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
